# Generated by Django 3.0.7 on 2020-06-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sale_types',
            new_name='sale_type',
        ),
    ]
